version: "3.3"

services:

  mariadb-container:
    image: linuxserver/mariadb:latest
    container_name: mariadb-container
    environment:
      PUID: 1000
      PGID: 1000
        - MYSQL_USER="root"
        - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    restart: unless-stopped
    volumes:
      - ./db:/config
    networks:
      - backend

  rolling-avg-container:
    container_name: rolling-avg-container
    depends_on:
      - mariadb-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./plots:/plots
    networks:
      - backend

networks:
  backend:
