version: "3.3"

services:

  mariadb-container:
    image: linuxserver/mariadb:latest  # I like this image more than the base one
    container_name: mariadb-container
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./db:/config
    networks:
      - backend

  colling-avg-container:
    container_name: colling-avg-container
    depends_on:
      - mariadb-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/results
    networks:
      - backend

networks:
  backend: